# Use an official OpenJDK image as the base
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy your jar file into the container (replace app.jar with your actual jar file name)
COPY patient-service.jar .

# Expose the port your app runs on (change if needed)
EXPOSE 5000

# Command to run the jar
CMD ["java", "-jar", "patient-service.jar"]